# Generated by Django 5.0.4 on 2024-05-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(blank=True, null=True, verbose_name="Сообщение"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Телефон"
            ),
        ),
    ]
