# Generated by Django 5.0.4 on 2024-06-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_version_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активная     "),
        ),
    ]
